using System;
using System.IO;
using Aspose.Cells;

namespace SummaryReportGenerator
{
    class Program
    {
        static void Main()
        {
            // Paths for the processed workbook and the summary output
            string processedFilePath = "ProcessedData.xlsx";
            string summaryFilePath = "SummaryReport.xlsx";

            // Ensure the processed workbook exists; create a sample if it does not
            if (!File.Exists(processedFilePath))
            {
                var sampleWorkbook = new Workbook();
                var ws = sampleWorkbook.Worksheets[0];
                ws.Cells["A1"].PutValue("Sample");
                ws.Cells["B2"].PutValue(123);
                sampleWorkbook.Save(processedFilePath, SaveFormat.Xlsx);
            }

            // Load the processed workbook
            Workbook processedWorkbook = new Workbook(processedFilePath);

            // Placeholder summary text (replace with actual AI integration if available)
            string summaryText = "Summary generated by application.";

            // Create a new workbook for the summary
            Workbook summaryWorkbook = new Workbook();

            // Access the first worksheet
            Worksheet sheet = summaryWorkbook.Worksheets[0];

            // Write the summary
            sheet.Cells["A1"].PutValue("Workbook Summary:");
            sheet.Cells["A2"].PutValue(summaryText);

            // Add key metrics
            sheet.Cells["A4"].PutValue("Key Metrics");
            sheet.Cells["A5"].PutValue("Number of Worksheets:");
            sheet.Cells["B5"].PutValue(processedWorkbook.Worksheets.Count);

            // Calculate total rows and columns across all worksheets
            int totalRows = 0;
            int totalColumns = 0;
            foreach (Worksheet ws in processedWorkbook.Worksheets)
            {
                totalRows += ws.Cells.MaxDataRow + 1;      // MaxDataRow is zero‑based
                totalColumns += ws.Cells.MaxDataColumn + 1;
            }

            sheet.Cells["A6"].PutValue("Total Data Rows:");
            sheet.Cells["B6"].PutValue(totalRows);
            sheet.Cells["A7"].PutValue("Total Data Columns:");
            sheet.Cells["B7"].PutValue(totalColumns);

            // Save the summary workbook
            summaryWorkbook.Save(summaryFilePath, SaveFormat.Xlsx);
        }
    }
}