using System;
using Aspose.Cells;

namespace AsposeCellsHeaderFooterDemo
{
    public class Program
    {
        public static void Main()
        {
            // Create a new workbook
            Workbook workbook = new Workbook();

            // -------------------------------------------------
            // Worksheet 1 - default header/footer with odd/even pages
            // -------------------------------------------------
            Worksheet sheet1 = workbook.Worksheets[0];
            sheet1.Name = "Report";

            // Access PageSetup for the first worksheet
            PageSetup ps1 = sheet1.PageSetup;

            // Enable different headers/footers for odd and even pages
            ps1.IsHFDiffOddEven = true;

            // Set odd page header/footer (standard)
            ps1.SetHeader(0, "&LReport - Odd Page");          // Left section
            ps1.SetHeader(1, "&C&\"Arial,Bold\"&12Page &P"); // Center section with page number
            ps1.SetHeader(2, "&R&\"Arial\"&10Date: &D");      // Right section with date
            ps1.SetFooter(0, "&LConfidential");              // Left footer
            ps1.SetFooter(1, "&C&\"Arial\"&8Page &P of &N"); // Center footer with page count
            ps1.SetFooter(2, "&R&\"Arial\"&10Generated by Aspose"); // Right footer

            // Set even page header/footer
            ps1.SetEvenHeader(0, "&LReport - Even Page");
            ps1.SetEvenHeader(1, "&C&\"Arial,Bold\"&12Even Page &P");
            ps1.SetEvenHeader(2, "&R&\"Arial\"&10Date: &D");
            ps1.SetEvenFooter(0, "&LInternal Use Only");
            ps1.SetEvenFooter(1, "&C&\"Arial\"&8Page &P of &N");
            ps1.SetEvenFooter(2, "&R&\"Arial\"&10Generated by Aspose");

            // -------------------------------------------------
            // Worksheet 2 - first page different from others
            // -------------------------------------------------
            int sheet2Index = workbook.Worksheets.Add();
            Worksheet sheet2 = workbook.Worksheets[sheet2Index];
            sheet2.Name = "Summary";

            // Access PageSetup for the second worksheet
            PageSetup ps2 = sheet2.PageSetup;

            // Enable different first page header/footer
            ps2.IsHFDiffFirst = true;

            // Set first page header/footer
            ps2.SetFirstPageHeader(0, "&LFirst Page Header");
            ps2.SetFirstPageHeader(1, "&C&\"Arial,Bold\"&14Summary Report");
            ps2.SetFirstPageHeader(2, "&R&\"Arial\"&10Date: &D");
            ps2.SetFirstPageFooter(0, "&LFirst Page Footer");
            ps2.SetFirstPageFooter(1, "&C&\"Arial\"&8Page &P of &N");
            ps2.SetFirstPageFooter(2, "&R&\"Arial\"&10Confidential");

            // Set standard header/footer for remaining pages
            ps2.SetHeader(0, "&LStandard Header");
            ps2.SetHeader(1, "&C&\"Arial\"&12Page &P");
            ps2.SetHeader(2, "&R&\"Arial\"&10Company");
            ps2.SetFooter(0, "&LStandard Footer");
            ps2.SetFooter(1, "&C&\"Arial\"&8Page &P of &N");
            ps2.SetFooter(2, "&R&\"Arial\"&10Generated on &D");

            // -------------------------------------------------
            // Save the workbook to a file
            // -------------------------------------------------
            workbook.Save("DistinctHeadersFooters.xlsx");

            // -------------------------------------------------
            // Load the saved workbook to verify settings (optional)
            // -------------------------------------------------
            Workbook loaded = new Workbook("DistinctHeadersFooters.xlsx");
            Console.WriteLine("Workbook saved and reloaded successfully.");
        }
    }
}