using System;
using Aspose.Cells;

namespace WorkbookHeaderFooterDemo
{
    class Program
    {
        static void Main()
        {
            // Create a new workbook (uses the provided Workbook constructor rule)
            Workbook workbook = new Workbook();

            // Add a few worksheets for demonstration
            int sheetCount = 3;
            for (int i = 1; i < sheetCount; i++)
            {
                workbook.Worksheets.Add();
            }

            // Iterate through each worksheet and configure headers and footers
            foreach (Worksheet sheet in workbook.Worksheets)
            {
                // Access the PageSetup object of the current worksheet
                PageSetup pageSetup = sheet.PageSetup;

                // Enable different headers/footers for the first page and for odd/even pages
                pageSetup.IsHFDiffFirst = true;      // First page can have its own header/footer
                pageSetup.IsHFDiffOddEven = true;    // Odd and even pages can differ

                // ----- Common Header/Footer (applies to odd pages) -----
                // Left header: file name without path
                pageSetup.SetHeader(0, "&F");
                // Center header: custom text with page number and total pages
                pageSetup.SetHeader(1, "Report - Page &P of &N");
                // Right header: current date
                pageSetup.SetHeader(2, "&D");

                // Left footer: confidential notice
                pageSetup.SetFooter(0, "Confidential");
                // Center footer: page number
                pageSetup.SetFooter(1, "Page &P");
                // Right footer: company name
                pageSetup.SetFooter(2, "Acme Corp");

                // ----- Even Page Header/Footer (different from odd pages) -----
                // Even page left header: custom text
                pageSetup.SetEvenHeader(0, "Even Page Left Header");
                // Even page center header: page number only
                pageSetup.SetEvenHeader(1, "Page &P");
                // Even page right header: current time
                pageSetup.SetEvenHeader(2, "&T");

                // Even page left footer: same confidential notice
                pageSetup.SetEvenFooter(0, "Confidential");
                // Even page center footer: page number of total pages
                pageSetup.SetEvenFooter(1, "Page &P of &N");
                // Even page right footer: company website
                pageSetup.SetEvenFooter(2, "www.acme.com");

                // ----- First Page Header/Footer (different from other pages) -----
                // First page left header: special title
                pageSetup.SetFirstPageHeader(0, "&\"Arial,Bold\"&12First Page Title");
                // First page center header: empty
                pageSetup.SetFirstPageHeader(1, "");
                // First page right header: sheet name
                pageSetup.SetFirstPageHeader(2, "&A");

                // First page left footer: document version
                pageSetup.SetFirstPageFooter(0, "Version 1.0");
                // First page center footer: empty
                pageSetup.SetFirstPageFooter(1, "");
                // First page right footer: generated by user
                pageSetup.SetFirstPageFooter(2, "Generated by System");
            }

            // Save the workbook (uses the provided Workbook.Save rule)
            workbook.Save("WorkbookHeadersFootersDemo.xlsx");
        }
    }
}