using System;
using System.IO;
using Aspose.Cells;

namespace AsposeCellsDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            // Path to the existing Excel file to be opened
            string inputPath = "InputWorkbook.xlsx";

            // Open the workbook using the constructor that accepts a file name
            Workbook workbook = new Workbook(inputPath);

            // Access the first worksheet (index 0)
            Worksheet firstSheet = workbook.Worksheets[0];

            // Modify some cells in the first worksheet
            firstSheet.Cells["A1"].PutValue("Updated Header");
            firstSheet.Cells["B2"].PutValue(12345);
            firstSheet.Cells["C3"].Formula = "=SUM(B2:B10)";

            // Add a new worksheet to the workbook
            int newSheetIndex = workbook.Worksheets.Add();
            Worksheet newSheet = workbook.Worksheets[newSheetIndex];
            newSheet.Name = "Summary";

            // Populate the new worksheet with data
            newSheet.Cells["A1"].PutValue("Report Summary");
            newSheet.Cells["A2"].PutValue(DateTime.Now);
            newSheet.Cells["B2"].PutValue("Generated by Aspose.Cells");

            // Save the modified workbook to a new file using the simple Save(string) overload
            string outputPath1 = "ModifiedWorkbook.xlsx";
            workbook.Save(outputPath1);

            // Save the same workbook to PDF format using the Save(string, SaveFormat) overload
            string outputPath2 = "ModifiedWorkbook.pdf";
            workbook.Save(outputPath2, SaveFormat.Pdf);

            // Demonstrate saving to a memory stream (Excel 97-2003 format) and then creating a workbook from that stream
            using (MemoryStream stream = workbook.SaveToStream())
            {
                // Reset stream position before reading
                stream.Position = 0;

                // Load a new workbook from the memory stream
                Workbook streamWorkbook = new Workbook(stream);

                // Make an additional change
                streamWorkbook.Worksheets[0].Cells["D4"].PutValue("Added via stream");

                // Save the stream-based workbook to another file
                string outputPath3 = "StreamBasedWorkbook.xls";
                streamWorkbook.Save(outputPath3);
                streamWorkbook.Dispose();
            }

            // Clean up
            workbook.Dispose();

            Console.WriteLine("Workbook processing completed.");
        }
    }
}